/**
 * Codex config.toml ownership splicing.
 *
 * Mimir regenerates its config.toml on every install/update, but Codex
 * writes its OWN state into the same file at runtime (verified on
 * 0.144.0: a bare top-level `personality` key and `[projects."…"]`
 * trust_level sections). A blind regenerate wiped that state — every
 * update re-prompted the user to trust each project.
 *
 * Ownership is marker-based: everything mimir writes (rendered template
 * + hook-trust ledger) lives between BEGIN/END marker comments. On
 * regenerate, the existing file's content OUTSIDE the markers is
 * preserved in place — prefix stays prefix, suffix stays suffix, which
 * matters because TOML bare top-level keys must precede any [section].
 *
 * Files from before the markers existed get a salvage pass: bare
 * top-level keys ahead of the first section become the prefix, and
 * `[projects.*]` sections (the codex state that actually hurts to lose)
 * become the suffix; the rest was mimir's and is replaced wholesale.
 */

export const MANAGED_BEGIN =
  "# >>> MIMIR MANAGED — regenerated by install/update; do not edit this block >>>";
export const MANAGED_END = "# <<< MIMIR MANAGED <<<";

const wrapManaged = (rendered: string) =>
  `${MANAGED_BEGIN}\n${rendered.trimEnd()}\n${MANAGED_END}\n`;

const SECTION_HEADER = /^\s*\[/;
const BARE_KEY = /^\s*[A-Za-z0-9_-]+\s*=/;
const PROJECTS_HEADER = /^\s*\[projects\./;

/**
 * Salvage codex-owned content from a marker-less (pre-marker) file:
 * bare top-level keys before the first section, and every [projects.*]
 * section body.
 */
const salvage = (existing: string) => {
  const lines = existing.split("\n");

  const prefix: string[] = [];
  for (const line of lines) {
    if (SECTION_HEADER.test(line)) break;
    if (BARE_KEY.test(line)) prefix.push(line);
  }

  const suffix: string[] = [];
  let inProjects = false;
  for (const line of lines) {
    if (SECTION_HEADER.test(line)) {
      inProjects = PROJECTS_HEADER.test(line);
    }
    if (inProjects) suffix.push(line);
  }

  return { prefix: prefix.join("\n"), suffix: suffix.join("\n") };
};

/**
 * Produce the full new config.toml content: the freshly rendered
 * mimir-managed block spliced into whatever codex-owned content the
 * existing file carries. `existing` is null on first install.
 */
export const spliceManagedConfig = (
  existing: string | null,
  rendered: string,
) => {
  if (existing === null) return wrapManaged(rendered);

  const beginAt = existing.indexOf(MANAGED_BEGIN);
  const endAt = existing.indexOf(MANAGED_END);

  if (beginAt !== -1 && endAt !== -1 && endAt > beginAt) {
    const prefix = existing.slice(0, beginAt);
    const suffix = existing.slice(endAt + MANAGED_END.length);
    return `${prefix}${wrapManaged(rendered)}${suffix.replace(/^\n/, "")}`;
  }

  // Pre-marker file: salvage codex-owned pieces, discard old mimir body.
  const { prefix, suffix } = salvage(existing);
  const parts = [];
  if (prefix.length > 0) parts.push(`${prefix}\n`);
  parts.push(wrapManaged(rendered));
  if (suffix.length > 0) parts.push(`${suffix}\n`);
  return parts.join("");
};

/**
 * Insert the hook-trust ledger INSIDE the managed block (immediately
 * before the END marker) so the next regenerate replaces it along with
 * the rest of mimir's content. Appends when markers are absent — the
 * pre-marker fallback trust.ts always had.
 */
export const insertTrustSection = (content: string, trustToml: string) => {
  const endAt = content.indexOf(MANAGED_END);
  if (endAt === -1) return `${content}${trustToml}`;
  return `${content.slice(0, endAt)}${trustToml.trimEnd()}\n${content.slice(endAt)}`;
};
