import { describe, expect, test } from "bun:test";
import {
  insertTrustSection,
  MANAGED_BEGIN,
  MANAGED_END,
  spliceManagedConfig,
} from "./config-preserve";

const RENDERED_V1 = "[features]\ncode_mode_host = false";
const RENDERED_V2 = "[features]\ncode_mode_host = true";

describe("spliceManagedConfig", () => {
  test("first install wraps the rendered block in markers", () => {
    const out = spliceManagedConfig(null, RENDERED_V1);
    expect(out.startsWith(MANAGED_BEGIN)).toBe(true);
    expect(out).toContain("code_mode_host = false");
    expect(out.trimEnd().endsWith(MANAGED_END)).toBe(true);
  });

  test("regenerate replaces the managed block, preserving codex content in place", () => {
    const first = spliceManagedConfig(null, RENDERED_V1);
    // Codex writes a bare key at the top and a projects section at the
    // bottom — exactly what 0.144.0 did during the live smoke.
    const codexEdited = `personality = "pragmatic"\n${first}[projects."/Users/me/proj"]\ntrust_level = "trusted"\n`;

    const regenerated = spliceManagedConfig(codexEdited, RENDERED_V2);

    // Bare key still FIRST (TOML: top-level keys must precede sections).
    expect(regenerated.startsWith('personality = "pragmatic"')).toBe(true);
    // New managed content in, old managed content out.
    expect(regenerated).toContain("code_mode_host = true");
    expect(regenerated).not.toContain("code_mode_host = false");
    // Projects trust preserved after the managed block.
    expect(regenerated).toContain('[projects."/Users/me/proj"]');
    expect(regenerated.indexOf('trust_level = "trusted"')).toBeGreaterThan(
      regenerated.indexOf(MANAGED_END),
    );
  });

  test("pre-marker files get a salvage pass: bare keys + projects survive", () => {
    const legacy = [
      'personality = "pragmatic"',
      "# Mimir-owned Codex config — regenerated by `mimir-codex-bin install`.",
      "[features]",
      "code_mode_host = false",
      "[mcp_servers.mimir]",
      'url = "https://old.example.com/mcp"',
      '[hooks.state."/x/config.toml:stop:0:0"]',
      "enabled = true",
      '[projects."/tmp/proj"]',
      'trust_level = "trusted"',
    ].join("\n");

    const out = spliceManagedConfig(legacy, RENDERED_V2);

    expect(out.startsWith('personality = "pragmatic"')).toBe(true);
    expect(out).toContain('[projects."/tmp/proj"]');
    expect(out).toContain("code_mode_host = true");
    // Old mimir body (stale URL, stale trust ledger) is gone.
    expect(out).not.toContain("old.example.com");
    expect(out).not.toContain('hooks.state."/x/config.toml');
  });

  test("regenerate is idempotent for codex content across repeated updates", () => {
    const first = spliceManagedConfig(null, RENDERED_V1);
    const withCodex = `${first}[projects."/p"]\ntrust_level = "trusted"\n`;
    const second = spliceManagedConfig(withCodex, RENDERED_V2);
    const third = spliceManagedConfig(second, RENDERED_V1);
    const occurrences = third.split('[projects."/p"]').length - 1;
    expect(occurrences).toBe(1);
  });
});

describe("insertTrustSection", () => {
  test("lands inside the managed block, replaced on regenerate", () => {
    const content = spliceManagedConfig(null, RENDERED_V1);
    const trusted = insertTrustSection(
      content,
      '\n[hooks.state."/a:stop:0:0"]\nenabled = true\n',
    );
    expect(trusted.indexOf('hooks.state."/a:stop:0:0"')).toBeLessThan(
      trusted.indexOf(MANAGED_END),
    );

    // A later regenerate drops the old ledger with the rest of the block.
    const regenerated = spliceManagedConfig(trusted, RENDERED_V2);
    expect(regenerated).not.toContain('hooks.state."/a:stop:0:0"');
  });

  test("appends when markers are absent", () => {
    const out = insertTrustSection("no markers here\n", "\n[hooks.state]\n");
    expect(out).toContain("[hooks.state]");
  });
});
