/**
 * Hook trust automation (verified against codex-cli 0.144.0).
 *
 * Codex silently skips "unmanaged" hooks until each definition is
 * trusted: a `[hooks.state."<sourcePath>:<event>:<group>:<hook>"]` entry
 * in config.toml carrying `enabled = true` and the definition's
 * `trusted_hash` (sha256 over the normalised hook identity). Computing
 * that hash ourselves would chase Codex's canonicalisation; instead we
 * ask Codex for it — `codex app-server` (JSON-RPC over stdio) exposes
 * `hooks/list`, which returns every discovered hook's key and
 * currentHash.
 *
 * Flow: spawn app-server with CODEX_HOME pointed at the mimir home →
 * initialize → hooks/list → filter to hooks sourced from OUR config.toml
 * → append a fresh [hooks.state] section. The installer regenerates
 * config.toml from the template first, so appending never duplicates.
 */

import { join } from "node:path";
import { attempt, attemptSync } from "@mimir/plugin-core/result";
import { insertTrustSection } from "./config-preserve";
import { createLogger } from "./logger";

const log = createLogger("trust");

type ListedHook = {
  readonly key?: string;
  readonly sourcePath?: string;
  readonly isManaged?: boolean;
  readonly currentHash?: string;
  readonly trustStatus?: string;
};

type HooksListResult = {
  readonly data?: readonly {
    readonly hooks?: readonly ListedHook[];
  }[];
};

type RpcMessage = {
  readonly id?: number;
  readonly result?: HooksListResult;
  readonly error?: { readonly message?: string };
};

const APP_SERVER_TIMEOUT_MS = 20_000;

/**
 * Query `codex app-server` for every hook it discovers under the given
 * CODEX_HOME. Returns the raw hook list or an error string (codex
 * missing, timeout, protocol failure).
 */
export const listHooks = async (codexHome: string, cwd: string) => {
  const [spawnErr, proc] = attemptSync(() =>
    Bun.spawn(["codex", "app-server"], {
      env: { ...process.env, CODEX_HOME: codexHome },
      stdin: "pipe",
      stdout: "pipe",
      stderr: "ignore",
    }),
  );
  if (spawnErr) {
    return { error: `failed to spawn codex app-server: ${spawnErr.message}` };
  }

  const send = (msg: unknown) => {
    proc.stdin.write(`${JSON.stringify(msg)}\n`);
  };

  send({
    method: "initialize",
    id: 1,
    params: {
      clientInfo: {
        name: "mimir-codex",
        title: "Mimir",
        version: "1.0.0",
      },
    },
  });

  const outcome = await new Promise<
    { hooks: ListedHook[] } | { error: string }
  >((resolve) => {
    const timer = setTimeout(() => {
      resolve({ error: "timed out waiting for codex app-server" });
    }, APP_SERVER_TIMEOUT_MS);

    const finish = (value: { hooks: ListedHook[] } | { error: string }) => {
      clearTimeout(timer);
      resolve(value);
    };

    (async () => {
      const decoder = new TextDecoder();
      let buffer = "";
      let initialized = false;

      for await (const chunk of proc.stdout) {
        buffer += decoder.decode(chunk);
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          if (line.trim().length === 0) continue;
          const [parseErr, msg] = attemptSync(
            () => JSON.parse(line) as RpcMessage,
          );
          if (parseErr) continue;

          if (msg.id === 1 && !initialized) {
            initialized = true;
            send({ method: "initialized" });
            send({ method: "hooks/list", id: 2, params: { cwd: [cwd] } });
            continue;
          }
          if (msg.id === 2) {
            if (msg.error) {
              finish({
                error: `hooks/list failed: ${msg.error.message ?? "unknown"}`,
              });
              return;
            }
            const hooks = (msg.result?.data ?? []).flatMap(
              (entry) => entry.hooks ?? [],
            );
            finish({ hooks: [...hooks] });
            return;
          }
        }
      }
      finish({ error: "codex app-server closed before responding" });
    })().catch((err) =>
      finish({ error: err instanceof Error ? err.message : String(err) }),
    );
  });

  proc.kill();
  return outcome;
};

const TRUST_SECTION_HEADER =
  "\n# ── Hook trust ledger (generated by mimir-codex-bin install) ──────────\n";

/**
 * Trust every mimir hook defined in `<codexHome>/config.toml` by
 * appending [hooks.state] entries with each hook's currentHash. Returns
 * the number of hooks trusted, or an error message when Codex could not
 * be queried — the installer surfaces it as a warning (hooks stay dark
 * until a re-run) rather than failing the whole install.
 */
export const trustMimirHooks = async (codexHome: string) => {
  const listed = await listHooks(codexHome, process.cwd());
  if ("error" in listed) return { trusted: 0, error: listed.error };

  const configPath = join(codexHome, "config.toml");
  const ours = listed.hooks.filter(
    (hook) =>
      hook.isManaged === false &&
      hook.key &&
      hook.currentHash &&
      hook.sourcePath === configPath,
  );
  // Symlink/canonicalisation drift (e.g. /tmp vs /private/tmp on macOS)
  // can make sourcePath differ from the path we wrote — fall back to
  // matching on the basename's directory being our home.
  const matched =
    ours.length > 0
      ? ours
      : listed.hooks.filter(
          (hook) =>
            hook.isManaged === false &&
            hook.key &&
            hook.currentHash &&
            hook.sourcePath?.endsWith("/config.toml") &&
            hook.sourcePath.includes("/codex"),
        );

  if (matched.length === 0) {
    return { trusted: 0, error: "no mimir hooks discovered to trust" };
  }

  const lines = [TRUST_SECTION_HEADER];
  for (const hook of matched) {
    lines.push(
      `[hooks.state."${hook.key}"]`,
      "enabled = true",
      `trusted_hash = "${hook.currentHash}"`,
      "",
    );
  }

  const [readErr, existing] = await attempt(() => Bun.file(configPath).text());
  if (readErr) {
    return { trusted: 0, error: `config.toml unreadable: ${readErr.message}` };
  }
  // Inside the managed block — the next regenerate replaces the ledger
  // along with the rest of mimir's content instead of orphaning it.
  await Bun.write(configPath, insertTrustSection(existing, lines.join("\n")));

  log.info("hook trust ledger written", {
    configPath,
    trusted: matched.length,
  });
  return { trusted: matched.length, error: null };
};
